[DATABASE]
ENGINE = djongo
NAME = nesplConfig
ENFORCE_SCHEMA = True

[MONGODB]
#HOST = 10.0.0.14
HOST = 10.0.0.14
PORT = 27017
# Server port : 8000
USERNAME = spectauser
PASSWORD = spectaDb#011
AUTH_SOURCE = nesplConfig
AUTH_MECHANISM = SCRAM-SHA-256

[SECRET_KEY]
key = django-insecure-1&mdhg^khpaem1&j_9=v=g+l%_=f)m&rmqnt(glrf6z4rvlj%0

[CONSTANTS]
MAX_LEVELS = 3
#QUESTIONS_PER_LEVEL = 30
#QUESTIONS_PER_ASSE_TYPE = 90 
MAX_SCORE = 132